version: '{build}'
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019

clone_script:
- cmd: git clone -q --branch=master --recursive https://github.com/CypherCore/CypherCore.git C:\projects\CypherCore-master

build_script:
- cmd: >-
    cd "C:/projects/CypherCore-master"

    dotnet restore

    dotnet build /p:Platform=win-x64
